# Explore here

# Pip & Requirements

In [107]:
pip install -r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: ipyleaflet>=0.14.0 in /home/vscode/.local/lib/python3.11/site-packages (from -r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 1)) (0.17.4)
Requirement already satisfied: ipywidgets>=7.7.1 in /home/vscode/.local/lib/python3.11/site-packages (from -r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 2)) (8.1.1)
Requirement already satisfied: matplotlib>=3.7.0 in /home/vscode/.local/lib/python3.11/site-packages (from -r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 3)) (3.8.0)
Requirement already satisfied: numpy>=1.24.2 in /home/vscode/.local/lib/python3.11/site-packages (from -r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 4)) (1.26.1)
Requirement already satisfied: opencv-python>=4.1.2 in /home/vscode/.local/lib/python3.11/site-packages (from -r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 5)) (4.8.1.78)
Requirement already satisfied: pandas>=1.5.3 in /home/vscode/.local/lib/python3.11/site-packages (from -r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 6)) (2.1.2)
Requirement already satisfied: psycopg2-binary>=2.9.3 in /home/vscode/.local/lib/python3.11/site-packages (from -r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 7)) (2.9.9)
Requirement already satisfied: pymysql>=1.0.2 in /home/vscode/.local/lib/python3.11/site-packages (from -r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 8)) (1.1.0)
Requirement already satisfied: python-dotenv>=0.20.0 in /home/vscode/.local/lib/python3.11/site-packages (from -r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 9)) (1.0.0)
Requirement already satisfied: requests>=2.27.1 in /home/vscode/.local/lib/python3.11/site-packages (from -r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 10)) (2.31.0)
Requirement already satisfied: scikit-learn in /home/vscode/.local/lib/python3.11/site-packages (from -r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 11)) (1.3.2)
Requirement already satisfied: seaborn>=0.12.2 in /home/vscode/.local/lib/python3.11/site-packages (from -r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 12)) (0.13.0)
Requirement already satisfied: sqlalchemy>=1.4.37 in /home/vscode/.local/lib/python3.11/site-packages (from -r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 13)) (2.0.22)
Requirement already satisfied: sympy>=1.10.1 in /home/vscode/.local/lib/python3.11/site-packages (from -r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 14)) (1.12)
Requirement already satisfied: xgboost in /home/vscode/.local/lib/python3.11/site-packages (from -r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 15)) (2.0.1)
Requirement already satisfied: traittypes<3,>=0.2.1 in /home/vscode/.local/lib/python3.11/site-packages (from ipyleaflet>=0.14.0->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 1)) (0.2.1)
Requirement already satisfied: xyzservices>=2021.8.1 in /home/vscode/.local/lib/python3.11/site-packages (from ipyleaflet>=0.14.0->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 1)) (2023.10.1)
Requirement already satisfied: branca>=0.5.0 in /home/vscode/.local/lib/python3.11/site-packages (from ipyleaflet>=0.14.0->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 1)) (0.6.0)
Requirement already satisfied: comm>=0.1.3 in /home/vscode/.local/lib/python3.11/site-packages (from ipywidgets>=7.7.1->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 2)) (0.1.4)
Requirement already satisfied: ipython>=6.1.0 in /home/vscode/.local/lib/python3.11/site-packages (from ipywidgets>=7.7.1->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 2)) (8.17.1)
Requirement already satisfied: traitlets>=4.3.1 in /home/vscode/.local/lib/python3.11/site-packages (from ipywidgets>=7.7.1->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 2)) (5.13.0)
Requirement already satisfied: widgetsnbextension~=4.0.9 in /home/vscode/.local/lib/python3.11/site-packages (from ipywidgets>=7.7.1->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 2)) (4.0.9)
Requirement already satisfied: jupyterlab-widgets~=3.0.9 in /home/vscode/.local/lib/python3.11/site-packages (from ipywidgets>=7.7.1->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 2)) (3.0.9)
Requirement already satisfied: contourpy>=1.0.1 in /home/vscode/.local/lib/python3.11/site-packages (from matplotlib>=3.7.0->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 3)) (1.1.1)
Requirement already satisfied: cycler>=0.10 in /home/vscode/.local/lib/python3.11/site-packages (from matplotlib>=3.7.0->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 3)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/vscode/.local/lib/python3.11/site-packages (from matplotlib>=3.7.0->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 3)) (4.43.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/vscode/.local/lib/python3.11/site-packages (from matplotlib>=3.7.0->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 3)) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /home/vscode/.local/lib/python3.11/site-packages (from matplotlib>=3.7.0->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 3)) (23.2)
Requirement already satisfied: pillow>=6.2.0 in /home/vscode/.local/lib/python3.11/site-packages (from matplotlib>=3.7.0->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 3)) (10.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /home/vscode/.local/lib/python3.11/site-packages (from matplotlib>=3.7.0->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 3)) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /home/vscode/.local/lib/python3.11/site-packages (from matplotlib>=3.7.0->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 3)) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/vscode/.local/lib/python3.11/site-packages (from pandas>=1.5.3->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 6)) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /home/vscode/.local/lib/python3.11/site-packages (from pandas>=1.5.3->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 6)) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/vscode/.local/lib/python3.11/site-packages (from requests>=2.27.1->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 10)) (3.3.1)
Requirement already satisfied: idna<4,>=2.5 in /home/vscode/.local/lib/python3.11/site-packages (from requests>=2.27.1->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 10)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/vscode/.local/lib/python3.11/site-packages (from requests>=2.27.1->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 10)) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /home/vscode/.local/lib/python3.11/site-packages (from requests>=2.27.1->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 10)) (2023.7.22)
Requirement already satisfied: scipy>=1.5.0 in /home/vscode/.local/lib/python3.11/site-packages (from scikit-learn->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 11)) (1.11.3)
Requirement already satisfied: joblib>=1.1.1 in /home/vscode/.local/lib/python3.11/site-packages (from scikit-learn->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 11)) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/vscode/.local/lib/python3.11/site-packages (from scikit-learn->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 11)) (3.2.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /home/vscode/.local/lib/python3.11/site-packages (from sqlalchemy>=1.4.37->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 13)) (4.8.0)
Requirement already satisfied: greenlet!=0.4.17 in /home/vscode/.local/lib/python3.11/site-packages (from sqlalchemy>=1.4.37->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 13)) (3.0.1)
Requirement already satisfied: mpmath>=0.19 in /home/vscode/.local/lib/python3.11/site-packages (from sympy>=1.10.1->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 14)) (1.3.0)
Requirement already satisfied: jinja2 in /home/vscode/.local/lib/python3.11/site-packages (from branca>=0.5.0->ipyleaflet>=0.14.0->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 1)) (3.1.2)
Requirement already satisfied: decorator in /home/vscode/.local/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets>=7.7.1->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 2)) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /home/vscode/.local/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets>=7.7.1->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 2)) (0.19.1)
Requirement already satisfied: matplotlib-inline in /home/vscode/.local/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets>=7.7.1->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 2)) (0.1.6)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in /home/vscode/.local/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets>=7.7.1->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 2)) (3.0.39)
Requirement already satisfied: pygments>=2.4.0 in /home/vscode/.local/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets>=7.7.1->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 2)) (2.16.1)
Requirement already satisfied: stack-data in /home/vscode/.local/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets>=7.7.1->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 2)) (0.6.3)
Requirement already satisfied: pexpect>4.3 in /home/vscode/.local/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets>=7.7.1->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 2)) (4.8.0)
Requirement already satisfied: six>=1.5 in /home/vscode/.local/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib>=3.7.0->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 3)) (1.16.0)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /home/vscode/.local/lib/python3.11/site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets>=7.7.1->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 2)) (0.8.3)
Requirement already satisfied: ptyprocess>=0.5 in /home/vscode/.local/lib/python3.11/site-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets>=7.7.1->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 2)) (0.7.0)
Requirement already satisfied: wcwidth in /home/vscode/.local/lib/python3.11/site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython>=6.1.0->ipywidgets>=7.7.1->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 2)) (0.2.8)
Requirement already satisfied: MarkupSafe>=2.0 in /home/vscode/.local/lib/python3.11/site-packages (from jinja2->branca>=0.5.0->ipyleaflet>=0.14.0->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 1)) (2.1.3)
Requirement already satisfied: executing>=1.2.0 in /home/vscode/.local/lib/python3.11/site-packages (from stack-data->ipython>=6.1.0->ipywidgets>=7.7.1->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 2)) (2.0.1)
Requirement already satisfied: asttokens>=2.1.0 in /home/vscode/.local/lib/python3.11/site-packages (from stack-data->ipython>=6.1.0->ipywidgets>=7.7.1->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 2)) (2.4.1)
Requirement already satisfied: pure-eval in /home/vscode/.local/lib/python3.11/site-packages (from stack-data->ipython>=6.1.0->ipywidgets>=7.7.1->-r /workspaces/Logistic_Regression_Project_Tutorial/requirements.txt (line 2)) (0.2.2)

[notice] A new release of pip is available: 23.1.2 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [108]:
pip install seaborn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: seaborn in /home/vscode/.local/lib/python3.11/site-packages (0.13.0)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /home/vscode/.local/lib/python3.11/site-packages (from seaborn) (1.26.1)
Requirement already satisfied: pandas>=1.2 in /home/vscode/.local/lib/python3.11/site-packages (from seaborn) (2.1.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.3 in /home/vscode/.local/lib/python3.11/site-packages (from seaborn) (3.8.0)
Requirement already satisfied: contourpy>=1.0.1 in /home/vscode/.local/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.3->seaborn) (1.1.1)
Requirement already satisfied: cycler>=0.10 in /home/vscode/.local/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.3->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/vscode/.local/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.3->seaborn) (4.43.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/vscode/.local/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.3->seaborn) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /home/vscode/.local/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.3->seaborn) (23.2)
Requirement already satisfied: pillow>=6.2.0 in /home/vscode/.local/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.3->seaborn) (10.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /home/vscode/.local/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.3->seaborn) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /home/vscode/.local/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.3->seaborn) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/vscode/.local/lib/python3.11/site-packages (from pandas>=1.2->seaborn) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /home/vscode/.local/lib/python3.11/site-packages (from pandas>=1.2->seaborn) (2023.3)
Requirement already satisfied: six>=1.5 in /home/vscode/.local/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.3->seaborn) (1.16.0)

[notice] A new release of pip is available: 23.1.2 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

# All Imports

In [109]:
import os
import requests
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
import numpy as np
from sklearn.feature_selection import chi2, SelectKBest
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV

**Step 1: Data collection**

In [110]:
bank_data = pd.read_csv("https://raw.githubusercontent.com/4GeeksAcademy/logistic-regression-project-tutorial/main/bank-marketing-campaign-data.csv", sep = ";")
bank_data.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

**Step 2: Exploration and data cleaning**

In [111]:
bank_data.tail(5)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
41183,73,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41184,46,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41185,56,retired,married,university.degree,no,yes,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41186,44,technician,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41187,74,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,3,999,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no

In [112]:
bank_data.shape

(41188, 21)

In [113]:
bank_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41188 non-null  int64
 1   job             41188 non-null  object
 2   marital         41188 non-null  object
 3   education       41188 non-null  object
 4   default         41188 non-null  object
 5   housing         41188 non-null  object
 6   loan            41188 non-null  object
 7   contact         41188 non-null  object
 8   month           41188 non-null  object
 9   day_of_week     41188 non-null  object
 10  duration        41188 non-null  int64
 11  campaign        41188 non-null  int64
 12  pdays           41188 non-null  int64
 13  previous        41188 non-null  int64
 14  poutcome        41188 non-null  object
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null  float64
 18  euribor3m       41188 non-null  float64
 19  nr.employed     41188 non-null  float64
 20  y               41188 non-null  object
dtypes: float64(5), int64(5), object(11)
memory usage: 6.6+ MB

In [114]:
bank_data.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

Drop Duplicates

In [115]:
bank_data = bank_data.drop_duplicates().reset_index(drop = True)
bank_data.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

**Step 3: Min-Max scaler**

In [116]:
bank_data["job_n"] = pd.factorize(bank_data["job"])[0]
bank_data["marital_n"] = pd.factorize(bank_data["marital"])[0]
bank_data["education_n"] = pd.factorize(bank_data["education"])[0]
bank_data["default_n"] = pd.factorize(bank_data["default"])[0]
bank_data["housing_n"] = pd.factorize(bank_data["housing"])[0]
bank_data["loan_n"] = pd.factorize(bank_data["loan"])[0]
bank_data["contact_n"] = pd.factorize(bank_data["contact"])[0]
bank_data["month_n"] = pd.factorize(bank_data["month"])[0]
bank_data["day_of_week_n"] = pd.factorize(bank_data["day_of_week"])[0]
bank_data["poutcome_n"] = pd.factorize(bank_data["poutcome"])[0]
bank_data["y_n"] = pd.factorize(bank_data["y"])[0]
num_variables = ["job_n", "marital_n", "education_n", "default_n", "housing_n", "loan_n", "contact_n", "month_n", "day_of_week_n", "poutcome_n",
                 "age", "duration", "campaign", "pdays", "previous", "emp.var.rate", "cons.price.idx", "cons.conf.idx", "euribor3m", "nr.employed", "y_n"]

scaler = MinMaxScaler()
scal_features = scaler.fit_transform(bank_data[num_variables])
total_data_scal = pd.DataFrame(scal_features, index = bank_data.index, columns = num_variables)
total_data_scal.head()

,job_n,marital_n,education_n,default_n,housing_n,loan_n,contact_n,month_n,day_of_week_n,poutcome_n,...,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y_n
0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.053070,0.0,1.0,0.0,0.9375,0.698753,0.60251,0.957379,0.859735,0.0
1,0.090909,0.0,0.142857,0.5,0.0,0.0,0.0,0.0,0.0,0.0,...,0.030297,0.0,1.0,0.0,0.9375,0.698753,0.60251,0.957379,0.859735,0.0
2,0.090909,0.0,0.142857,0.0,0.5,0.0,0.0,0.0,0.0,0.0,...,0.045954,0.0,1.0,0.0,0.9375,0.698753,0.60251,0.957379,0.859735,0.0
3,0.181818,0.0,0.285714,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.030704,0.0,1.0,0.0,0.9375,0.698753,0.60251,0.957379,0.859735,0.0
4,0.090909,0.0,0.142857,0.0,0.0,0.5,0.0,0.0,0.0,0.0,...,0.062424,0.0,1.0,0.0,0.9375,0.698753,0.60251,0.957379,0.859735,0.0

**Step 3:Feature selection**

In [117]:
X = total_data_scal.drop("y_n", axis = 1)
y = total_data_scal["y_n"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 42)

selection_model = SelectKBest(chi2, k = 5)
selection_model.fit(X_train, y_train)
ix = selection_model.get_support()
X_train_sel = pd.DataFrame(selection_model.transform(X_train), columns = X_train.columns.values[ix])
X_test_sel = pd.DataFrame(selection_model.transform(X_test), columns = X_test.columns.values[ix])

X_train_sel.head()

   poutcome_n  previous  emp.var.rate  euribor3m  nr.employed
0         0.0       0.0      1.000000   0.980730     1.000000
1         0.0       0.0      0.333333   0.138291     0.512287
2         0.0       0.0      0.937500   0.956926     0.859735
3         0.0       0.0      0.937500   0.957379     0.859735
4         0.0       0.0      0.333333   0.175924     0.512287

In [118]:
X_test_sel.head()

   poutcome_n  previous  emp.var.rate  euribor3m  nr.employed
0         0.0  0.000000      0.104167   0.143278     0.425709
1         0.5  0.142857      0.333333   0.150759     0.512287
2         0.0  0.000000      0.479167   0.073679     0.000000
3         0.5  0.142857      0.333333   0.150759     0.512287
4         0.0  0.000000      1.000000   0.981410     1.000000

In [119]:
X_train_sel["y_n"] = list(y_train)
X_test_sel["y_n"] = list(y_test)
X_train_sel.to_csv("../data/processed/clean_train.csv", index = False)
X_test_sel.to_csv("../data/processed/clean_test.csv", index = False)

**Step 4:Logistic Regression model**

In [120]:
train_data = pd.read_csv("../data/processed/clean_train.csv")
test_data = pd.read_csv("../data/processed/clean_test.csv")

train_data.head()

   poutcome_n  previous  emp.var.rate  euribor3m  nr.employed  y_n
0         0.0       0.0      1.000000   0.980730     1.000000  0.0
1         0.0       0.0      0.333333   0.138291     0.512287  0.0
2         0.0       0.0      0.937500   0.956926     0.859735  0.0
3         0.0       0.0      0.937500   0.957379     0.859735  0.0
4         0.0       0.0      0.333333   0.175924     0.512287  0.0

In [121]:
X_train = train_data.drop(["y_n"], axis = 1)
y_train = train_data["y_n"]
X_test = test_data.drop(["y_n"], axis = 1)
y_test = test_data["y_n"]

In [122]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

**Accuracy of train data**

In [123]:
y_pred = model.predict(X_test)
y_pred

array([0., 0., 0., ..., 0., 0., 0.])

In [124]:
accuracy_score(y_test, y_pred)

0.8921806702282662

In [125]:
print(len(y_train))
print(len(y_pred))

37058
4118

In [126]:
# Check the alignment of data by comparing the lengths of y_train and y_pred
if len(y_train) != len(y_pred):
    print("Mismatched lengths between y_train and y_pred.")
else:
    print("Length of y_train:", len(y_train))
    print("Length of y_pred:", len(y_pred))

Mismatched lengths between y_train and y_pred.

**Step 5: Model optimization**

In [127]:
hyperparams = {
    "C": [0.001, 0.01, 0.1, 1, 10, 100, 1000],
    "penalty": ["l1", "l2", "elasticnet", None],
    "solver": ["newton-cg", "lbfgs", "liblinear", "sag", "saga"]
}

grid = GridSearchCV(model, hyperparams, scoring = "accuracy", cv = 10)
grid

GridSearchCV(cv=10, estimator=LogisticRegression(),
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000],
                         'penalty': ['l1', 'l2', 'elasticnet', None],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [128]:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn

grid.fit(X_train, y_train)

print(f"Best hyperparameters: {grid.best_params_}")

Best hyperparameters: {'C': 0.1, 'penalty': 'l2', 'solver': 'liblinear'}

In [129]:
model = LogisticRegression(C = 0.1, penalty = "l2", solver = "liblinear")
model.fit(X_train, y_train)

LogisticRegression(C=0.1, solver='liblinear')

In [130]:
y_pred = model.predict(X_test)
y_pred

array([0., 0., 0., ..., 0., 0., 0.])

In [131]:
accuracy_score(y_test, y_pred)

0.8938805245264692

In [132]:
from pickle import dump

dump(model, open("../models/logistic_regression_C-0.1_penalty-l2_solver-liblinear_42.sav", "wb"))